### PR TITLE
Use CRLF line endings

### PR DESCRIPTION
**Pull request by DecimalTurn**
As discussed in https://github.com/cristianbuse/VBA-FastDictionary/issues/6, I'm proposing to change line endings to make it easier for new comers to import parts of the project in the VBE. With this new configuration, files won't be converted to LF when saved into Git making the raw files available for direct import in the VBE after download.

I should also mention that I've worked on a [little write-up](https://github.com/DecimalTurn/VBA-on-GitHub?tab=readme-ov-file#gitattributes) regarding how to configure the .gitattributes file for VBA project. Let me know if you have comments/questions.

### CODE REVIEW

**Comment by DecimalTurn** [comment]
Since a changes to line endings makes the whole document look like it was change, I recommend looking at the changes using the `?w=1` param to ignore whitespace changes.
ie. : https://github.com/cristianbuse/VBA-FastDictionary/pull/7/files?w=1

**Comment by cristianbuse** [comment]
@DecimalTurn Many thanks for this! I did not know of your [VBA-on-GitHub](https://github.com/DecimalTurn/VBA-on-GitHub) repo but it is super useful.

**Comment by DecimalTurn** [comment]
My pleasure! I'll let you determine if you want to apply the same changes to your other projects, but feel free to tag me on those related issues if you'd like me to be involved. I think this project was the most crucial since the target audience can include a lot of new devs that aren't familiar with line engins issues.

Btw, when I looked at the .gitattributes file, I noticed that there was an issue with LFS. I'm pretty sure the line `git lfs track "*.png"` is the command that should be typed inside the command line (cmd or pwh) while the repo is selected as the current directory, not the line inside the .gitattributes file.

**Comment by DecimalTurn** [comment]
To be honest if it wasn't from Git complaning about while I was playing around in the terminal, I wouldn't have notice 😅.

**Comment by cristianbuse** [comment]
Many thanks Martin! I finally fixed the lfs.

**Pull request merged**
